term.clear()
term.setCursorPos(1,1)
print("Press any key here to open the boot menu.")
sleep(2)
term.setBackgroundColor(colors.blue)
term.clear()
term.setCursorPos(1,1)
local image1 = paintutils.loadImage(".boot/Enter-Key")
paintutils.drawImage(image1, 1, 2)
sleep(1)
term.setBackgroundColor(colors.blue)
term.clear()
term.setCursorPos(1,1)
term.setBackgroundColor(colors.blue)
local image2 = paintutils.loadImage(".boot/Enter-Key1")
paintutils.drawImage(image2, 1, 2)
sleep(1)
term.setBackgroundColor(colors.blue)
term.clear()
term.setCursorPos(1,1)
term.setBackgroundColor(colors.blue)
local image3 = paintutils.loadImage(".boot/Enter-Key2")
paintutils.drawImage(image3, 1, 2)
sleep(1)
term.setBackgroundColor(colors.blue)
term.clear()
term.setCursorPos(1,1)
term.setBackgroundColor(colors.blue)
local image4 = paintutils.loadImage(".boot/Enter-Key3")
paintutils.drawImage(image4, 1, 2)
sleep(1)
term.setBackgroundColor(colors.blue)
term.clear()
term.setCursorPos(1,1)
term.setBackgroundColor(colors.blue)
local image5 = paintutils.loadImage(".boot/Enter-Key4")
paintutils.drawImage(image5, 1, 2)
sleep(1)
term.setBackgroundColor(colors.blue)
term.clear()
term.setCursorPos(1,1)
term.setBackgroundColor(colors.blue)

local myTimer = os.startTimer(0)

while true do
  local event, par1 = os.pullEvent()

  if event == "timer" and par1 == myTimer then
    break
  elseif event == "key" then
    print("Start BootMenu...")
    term.setBackgroundColor(colors.black)
    sleep(1.261)
    term.clear()
    term.setCursorPos(1,1)
    shell.run("BootMenu")
    break
  end
end
