shell.run("delete MinuxNews.txt")
shell.run("pastebin get bJPTGeRF MinuxNews.txt")
term.clear()
term.setCursorPos(1,1)
term.setTextColor( colors.red )
h = fs.open("MinuxNews.txt", "r")
text = h.readAll()
h.close()
print(text)
term.setTextColor( colors.green )
print("Press Enter Key.")
read()