os.pullEvent=os.pullEventRaw
term.setBackgroundColor(colors.cyan)
term.clear()
sleep(0.3)
term.setBackgroundColor(colors.blue)
term.clear()



term.clear()
term.setCursorPos(23,10)
term.setTextColor(colors.green)
term.write("A")
term.setTextColor(colors.white)
term.write("P")
term.setTextColor(colors.yellow)
term.write("P")
term.setTextColor(colors.green)
term.write("L")
term.setTextColor(colors.cyan)
term.write("E")
term.setTextColor(colors.white)
term.write(" ")
term.setTextColor(colors.white)
term.write("O")
term.setTextColor(colors.white)
term.write("S")
sleep(2)
term.clear()

shell.run("1")

term.setBackgroundColor(colors.blue)
term.clear()
sleep(0.3)
term.setBackgroundColor(colors.cyan)
term.clear()
sleep(0.3)
term.setBackgroundColor(colors.black)
term.clear()
sleep(0.5)
shell.run("Login")
