term.clear()
term.setCursorPos(1,1)
textutils.slowPrint("Welcome To")
local image1 = paintutils.loadImage(".boot/1")
paintutils.drawImage(image1, 1, 1)
sleep(0.25)
local image2 = paintutils.loadImage(".boot/2")
paintutils.drawImage(image2, 1, 1)
sleep(0.25)
local image3 = paintutils.loadImage(".boot/3")
paintutils.drawImage(image3, 1, 1)
sleep(0.25)
local image4 = paintutils.loadImage(".boot/4")
paintutils.drawImage(image4, 1, 1)
sleep(0.25)
local image5 = paintutils.loadImage(".boot/5")
paintutils.drawImage(image5, 1, 1)
sleep(3)
term.setBackgroundColor(colors.black)
term.clear()
term.setCursorPos(1,1)
shell.run("Login.lua")
shell.run("Desktop")
