term.clear()
shell.run("rm startup.lua")
shell.run("rm Login.lua")
shell.run("rm Desktop.lua")
shell.run("rm FileManager.lua")
shell.run("rm MinuxNews.lua")
shell.run("rm update.lua")
shell.run("wget https://raw.githubusercontent.com/kazu55/MinuxGUI/main/startup.lua startup.lua")
shell.run("wget https://raw.githubusercontent.com/kazu55/MinuxGUI/main/Login.lua Login.lua")
shell.run("wget https://raw.githubusercontent.com/kazu55/MinuxGUI/main/Desktop.lua Desktop.lua")
shell.run("wget https://raw.githubusercontent.com/kazu55/MinuxGUI/main/MinuxNews.lua MinuxNews.lua")
shell.run("wget https://pastebin.com/raw/pnzdr8FB FileManager.lua")
shell.run("wget https://raw.githubusercontent.com/kazu55/MinuxGUI/master/update.lua update.lua")
os.reboot()
