term.clear()
term.setBackgroundColor(colors.black)
shell.run("rm startup.lua")
shell.run("rm Desktop.lua")
shell.run("rm FileManager.lua")
shell.run("rm MinuxNews.lua")
shell.run("rm update.lua")
shell.run("rm 1.lua")
shell.run("rm BootMenu.lua")
shell.run("rm shutdown1.lua")
shell.run("rm shutdown2.lua")
shell.run("rm errorMSG.lua")
shell.run("rm /.boot/")
shell.run("rm Login.lua")
shell.run("rm diaAPI.lua")
shell.run("pastebin get k7Gb1iMn startup")
os.reboot()
